### ISSUE TITLE
github actions windows performance

### ISSUE THREAD

**Issue by vitara-srinivasan** [alire-project/setup-alire#55]
It seems like setting up alr for github actions on windows takes a very very long time. Is there a prebuild executable of alr that can be used directly for windows actions?

or perhaps i am doing it all wrong.

appreciate your advice. Thanks, Srini

**Comment by Fabien-Chouteau** [comment]
What takes time is the installation of msys2 which is required to use Alire on Windows. I am not sure if we can speed up this installation.

**Comment by mosteo** [comment]
I think our latest https://github.com/alire-project/setup-alire at v2 should cache everything also on Windows and speed-up things considerably. @vitara-srinivasan , do you have an sample workflow run to inspect?

**Comment by vitara-srinivasan** [comment]
I do. Will run in a bit and let you
Know. Thanks,
Rajagopalan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vitara-srinivasan** [comment]
Is there something I should do in my yaml file to take advantage? I re ran but did not observe any changes. My .yaml is:

name: windows

on:
  push:
    branches: [ "bronze" ]
  pull_request:
    branches: [ "bronze" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: ***@***.***
      with:
        token:  ${{ secrets.ACTIONSBUILD }}
        submodules: true

    - name: Setup alr
      uses: ***@***.***
    - name: Build
      run: >
        python3 version.py ${{github.ref_name}} ${{github.sha}} ${{github.run_number}} ${{github.workflow}} ;
        cat revisions.ads ;
        mv revisions.ads src ;
        cd ./lib; source build.sh; cd ..;
        alr build ;
        bin/blog -h
      shell: bash

    - name: Publish
      uses: ***@***.***
      with:
          name: "artifacts"
          path: |
            bin/blog.exe

If you like, I can create a similar job in my public repo since above is private.

Regards, srini

Raja Srinivasan
Director, Software Engineering
Vitara Biomedical, Inc.
2929 Arch St. Suite 1535
Philadelphia, PA 19104
267-518-6300 ext 2006
***@***.***
***@***.***

**Comment by vitara-srinivasan** [comment]
https://github.com/RajaSrinivasan/letters/actions/workflows/winboxed.yml

The above is a public repo with a windows workflow - if you like to inspect.

Regards, srini

Raja Srinivasan
Director, Software Engineering
Vitara Biomedical, Inc.
2929 Arch St. Suite 1535
Philadelphia, PA 19104
267-518-6300 ext 2006
***@***.***
***@***.***

**Comment by mosteo** [comment]
Hi @vitara-srinivasan, I took a look at the workflow you posted. What I see there is that the cache was indeed used to set up `alr`, although that step still used 1:37 to complete... It's hard to see were that time was spent besides the cache download, as there's nothing very time-consuming there. 

Then, the build step took 8:57, which again seems a lot for the compilation of three files, unless they're very complex or generic-intensive... 

Not sure if the Windows VM was particularly sluggish in that run, but what I can say is that your workflow seems correct to me, and I can't see any time-wasting spots... Sorry for not having better feedback to offer at this time.

**Comment by mosteo** [comment]
Our latest v4 with #83 should have sped up Windows installations, in particular when cached. Please report any unexpected behaviors.
