### ISSUE TITLE
Cache for `~/.local`

### ISSUE THREAD

**Issue by reznikmm** [alire-project/setup-alire#68]
It looks like `alire-project/setup-alire@v3`  doesn't cache `$HOME/.local/share/alire/toolchains`. So GitHub Action successfully runs only first time. But when you run it second time `$HOME/.local/` isn't restored and there is no compilers on the system.

Could you check?

**Comment by mosteo** [comment]
I'll check. Still, the toolchain should be re-downloaded if missing, so suboptimal but not broken (in theory).

**Comment by reznikmm** [comment]
I've tried it today and it works! Thank you for the fix :+1:
